# Generated by Django 2.1.4 on 2019-01-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_delete_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
