# Generated by Django 2.1.4 on 2019-01-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_dev',
            field=models.BooleanField(default=False),
        ),
    ]
